### ISSUE TITLE
mid_x et mid_y comme seules coordonnées 

### ISSUE THREAD

**Issue by fabianmassart** [phacochr/phacochr#3]
Bonjour, 

J'ai réalisé un géocodage d'entreprises via phacochR. Dans mon code je rentre une colonne pour le code postal, une pour la rue et une pour le numéro de rue. 

Dans la table des résultats, j'obtiens bien une colonne "num_rue_clean" dont les numéros correspondent aux numéros de rue introduits, pourtant, je n'obtiens pas de coordonnées x et y basées sur ces numéros de rue mais uniquement des coordonnées basées sur la cordonnée médiane : mid_x et mid_y. PhacochèR ne semble pas se baser sur la colonne "num_rue_clean" pour calculer les coordonnées et semble procéder comme s'il n'avait pas reçu une information correcte. 

Je ne sais pas d'où vient le problème. Si vous avez une idée je suis preneur. 

Déjà merci. 

Fabian

**Comment by jgires** [comment]
Bonjour,

Très content de voir que notre géocodeur est utilisé !

En réalité, PhacochR produit à la fois les coordonnées du milieu de la rue (mid_x_31370 et mid_y_31370) et les coordonnées exactes (x_31370 et y_31370). Normalement, si le géocodage a réussi, l'output doit aussi comprendre les colonnes x_31370 et y_31370. Ce n'est pas le cas ? Ce serait étrange car il n'y a pas de situation où les colonnes x_31370 et y_31370 ne sont pas produites. Quel est le résultat du géocodage ? (Les "Statistiques concernant le géocodage" indiquées dans le petit tableau en fin de géocodage).

Très bonne fin de journée,

Joël Girès

**Comment by fabianmassart** [comment]
Bonjour, 

Merci d'avoir développé PhacochR, cela nous est très utile à l'Uliège ;) 

Je ne sais pas pour quelle raison, le "data_geocoded_sf" ne contenait pas ces données, par contre le "data_geocoded" bien. J'ai donc pu m'en sortir avec cet objet et cela a très bien fonctionné. 

Pour information, j'ai n'ai pas réussi à utiliser la fonction st_write, j'ai dès lors utilisé write_tsv(). J'ai ensuite importé le fichier dans ArcGis pour obtenir un shapefile. 

Merci pour votre réponse et excellente journée, 

Fabian Massart

**Comment by jgires** [comment]
Bonjour,

Très heureux que PhacochR soit utile à l'Uliège !

Il est normal que "data_geocoded_sf" ne comprenne pas les colonnes x_31370 et y_31370 : "data_geocoded_sf" est déjà un objet spatial. Il s'agit plus précisément d'un objet sf (https://r-spatial.github.io/sf/), qui contient une colonne "geometry" avec les coordonnées des adresses, permettant directement des traitements spatiaux.

La fonction st_write() ne fonctionne que sur un objet sf, et donc sur data_geocoded_sf, puisqu'elle est une fonction pour écrire des shp ou geopackages à partir d'un objet sf : https://r-spatial.github.io/sf/reference/st_write.html. Si cela n'a pas fonctionné, j'imagine que c'est parce que vous l'avez appliquée sur l'objet "data_geocoded", qui est un data.frame, et non un objet spatial.

N'hésitez pas si vous avez d'autres questions !
Bonne journée,

Joël Girès
