### ISSUE TITLE
Source de l'erreur inconnue

### ISSUE THREAD

**Issue by fabianmassart** [phacochr/phacochr#4]
Bonjour, 

Après l’utilisation de PhacochR, nous tentons d’identifier les éventuelles erreurs de recodage persistantes. Parmi ces erreurs, il en existent certaines dont nous ne parvenons pas à trouver la cause. Par exemple : La « Rue du Rivage » à Herstal est recodée en « Rue du Tige ». 
Auriez-vous une piste d’explication pour ce type de recodage. Ce pourrait-il que l’erreur soit due au fait que les deux noms aient trois lettres en commun  (i, g et e) ? . 

Par ailleurs, des éventuels changements de noms de rue sont-ils pris en compte par PhacochR ? Ce qui peut nous paraitre comme une erreur pourrait alors simplement être lié à une modification du nom de la rue. 

Déjà merci pour votre aide.

Cordialement, 

Fabian Massart

**Comment by jgires** [comment]
Bonjour Fabian,

Le principe de phacochr est de faire du matching probabiliste pour trouver l'adresse officielle BeST correspondant à la liste à géocoder, quand bien même il y a des fautes d'orthographe, de frappe, des mots manquants, etc. Il y a donc inévitablement des "faux positifs". L'erreur est limitée, car nous avons restreint le matching au sein du code postal indiqué et, si la rue est non trouvée, dans la commune et les communes adjacentes (option désactivable). Pour avoir une idée de la qualité des résultats, il est donc conseillé de vérifier plusieurs éléments, listés ici : https://phacochr.github.io/phacochr/index.html#r%C3%A9sultats-et-v%C3%A9rification-du-g%C3%A9ocodage.

Il faut savoir que la qualité du géocodage est dépendante de la qualité des données BeST, qui est notre base de données de référence. En Wallonie, il manque encore les coordonnées d'un petit % d'adresses. Nous vous recommandons de faire la mise à jours des données régulièrement : https://phacochr.github.io/phacochr/articles/data_phacochr.html. Pour info, les données BeST sont mises à jour toutes les semaines.

En regardant les données, BeST, je ne vois pas de "Rue du Rivage" à 4040 (Herstal). phacochr ne pourrait donc pas trouver cette rue si elle n'existe pas pour BeST. Je ne sais pas pourquoi elle ne figure pas dans BeST, si vous avez la réponse je suis intéressé. C'est la raison pour laquelle phacochr choisit une autre rue, celle qui lui ressemble le plus dans celles disponibles, a priori "Rue du Tige". Tous les géocodeurs fonctionnent à peu près de cette manière, ce n'est pas propre à phacochr.

Concernant les changements de nom, ils ne sont pas gérés, car BeST ne comprend que le dernier nom officiel. Il s'agit d'une limite, et nous désirons améliorer ce fonctionnement en important des alias pour les rues qui ont changé d'appellation récemment. Nous avons déjà des alias pour les rues (pour les différentes langues, avec ou sans prénom dans le nom, etc.), techniquement c'est donc prêt et facilement implémentable. Nous allons notamment le faire pour Charleroi. Mais il s'agit d'un travail laborieux à l'échelle de la Belgique, car il nécessite de récupérer des listes locales de changement de noms. N'hésitez pas si vous voulez contribuer pour Liège : nous pourrons intégrer les différentes appellations (avant-après changement de nom) !

Bonne journée,

Joël

**Comment by fabianmassart** [comment]
Bonjour Joël, 

Merci beaucoup pour ces informations, ça nous aide a y voir plus clair. Ces erreurs sont très très marginales, mais nous souhaitions avoir une idée de la cause. 

Nous ne savons pas non plus pourquoi la rue du Rivage ne figure pas dans BesT, nous avons rencontré eu très peu de cas de figure de la sorte. Peut-être est-ce du au fait qu'il s'agit d'une rue de desserte d'une zone industrielle. 

Bonne journée, 

Fabian

**Comment by jgires** [comment]
Rebonjour Fabian,

J'ai trouvé l'explication : la rue du Rivage à 4040 Herstal est bien dans BeST, mais elle est "vide" (elle est identifiée comme ne comprenant aucune adresse). Elle ne comprend donc aucune coordonnées X-Y. Elle a donc été exclue des données de phacochr (vu qu'il nous faut des coordonnées).

Vous avez une adresse précise à géocoder dans cette rue (avec numéro de police) ? Je ne vois aucun bâtiment sur openstreet map : https://www.openstreetmap.org/search?query=rue%20du%20rivage%204040#map=17/50.67730/5.64740.

**Comment by fabianmassart** [comment]
Bonjour Joël, 

Intéressant ! Pour la géolocalisation, nous sommes partis des données de la BCE. Dans ces données il y a une entreprise enregistrée au n°35 de la rue du Rivage. On la retrouve aussi sur Google Maps (https://www.google.com/maps/place/MATEGRO+SA/@50.6768785,5.6424174,17z/data=!3m1!4b1!4m6!3m5!1s0x47c0f1ada5c4a6c7:0x1bcb87af12d13444!8m2!3d50.6768785!4d5.6449923!16s%2Fg%2F1vm_x0c1?entry=ttu)

C'est donc simplement lié à une discordance entre les données BCE et Best. 

Bonne journée,
